### ISSUE TITLE
v0.18.0 not found on crates.io

### ISSUE THREAD

**Issue by KrullBorg** [omjadas/hudsucker#36] opened 2022-11-03 08:05 UTC
hi, i'm sorry but i'm very noob with rust so i think that this is a stupid question

i'm trying to use hudsucker; i put `hudsucker = "0.18.0"` on my Cargo.toml, but running `cargo build` i get

    Updating crates.io index
    error: failed to select a version for the requirement `hudsucker = "^0.18.0"`
    candidate versions found which didn't match: 0.16.1, 0.16.0, 0.15.0, ...
    location searched: crates.io index

it works using 0.16.1

what am i doing wrong?

thanks in advance

**Comment by omjadas** [comment] 2022-11-03 08:47
Could you please provide your entire `Cargo.toml` file?

**Comment by KrullBorg** [comment] 2022-11-03 08:57
[package]                                                                                                                                                                     
name = "pippo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html                                                                              

[dependencies]
hudsucker = "0.18.0"

**Comment by omjadas** [comment] 2022-11-03 10:13
Could you also let me know the output of `cargo --version`?

**Comment by KrullBorg** [comment] 2022-11-03 10:20
$ cargo --version
cargo 1.56.0

**Comment by omjadas** [comment] 2022-11-03 21:29
I believe the issue is that in hudsucker 0.17.0 I started using [namespaced dependencies and weak dependency features](https://blog.rust-lang.org/2022/04/07/Rust-1.60.0.html#new-syntax-for-cargo-features), which were introduced in rust 1.60.0. Assuming you are using rustup you can run `rustup update stable` to update to the latest stable version of rust (1.65.0 at the time of writing).

**Comment by KrullBorg** [comment] 2022-11-11 10:39
sorry for delay, i'll try asap to update rust (i'm using the version packaged on debian unstable)

**Comment by omjadas** [comment] 2022-12-26 03:31
@KrullBorg, can this issue be closed?

**Comment by omjadas** [comment] 2023-01-31 10:07
Closing, as I believe this has been addressed.

**Closed by omjadas** 2023-01-31 10:07 UTC
